---
dependency:
  name: galaxy
  options:
    role-file: molecule/win2019/requirements.yml
    requirements-file: molecule/win2019/requirements.yml
driver:
  name: vagrant
  provider:
    name: virtualbox
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: vagrant-win2019
    box: jborean93/WindowsServer2019
    memory: 2048
    instance_raw_config_args:
      - "vm.boot_timeout = 1200"
provisioner:
  name: ansible
  inventory:
    host_vars:
      vagrant-win2019:
        ansible_user: vagrant
        ansible_password: vagrant
        ansible_port: 55986
        ansible_host: 127.0.0.1
        ansible_connection: winrm
        ansible_winrm_transport: ntlm
        ansible_winrm_scheme: https
        ansible_winrm_server_cert_validation: ignore
        ansible_winrm_operation_timeout_sec: 200
        ansible_winrm_read_timeout_sec: 300
scenario:
  name: win2019
verifier:
  name: ansible
